packages: []

catalogs:

  build:
    '@iconify-json/carbon': ^1.2.11
    '@iconify-json/tabler': ^1.2.20
    '@vitejs/plugin-vue': ^6.0.0
    jsdom: ^26.1.0
    unocss: ^66.3.3
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.8.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.6

  dev:
    '@antfu/eslint-config': ^4.19.0
    '@types/node': ^24.1.0
    '@unocss/eslint-plugin': ^66.3.3
    '@vitest/ui': ^3.2.4
    '@vue-macros/volar': ^3.0.0-beta.17
    '@vue/test-utils': ^2.4.6
    dotenv: ^17.2.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.2
    msw: ^2.10.4
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vite-plugin-vue-devtools: ^7.7.7
    vitest: ^3.2.4
    vue-tsc: ^3.0.3

  frontend:
    '@pinia/colada': ^0.17.1
    '@vee-validate/zod': ^4.15.1
    '@vueuse/core': ^13.5.0
    '@vueuse/integrations': ^13.5.0

    dayjs: ^1.11.13
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ky: ^1.8.2
    nanoid: ^5.1.5
    pinia: ^3.0.3
    pinia-plugin-persistedstate-2: ^2.0.30
    vee-validate: ^4.15.1
    vue: ^3.5.18
    vue-final-modal: ^4.5.5
    vue-router: ^4.5.1
    zod: ^4.0.8

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
