catalogMode: prefer

shellEmulator: true

trustPolicy: off

packages: []
catalogs:
  build:
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/tabler': ^1.2.23
    '@vitejs/plugin-vue': ^6.0.3
    jsdom: ^27.3.0
    unocss: ^66.5.10
    unplugin: ^2.3.11
    unplugin-auto-import: ^20.3.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.19.1
    vite: ^7.3.0
  dev:
    '@antfu/eslint-config': ^6.7.1
    '@types/node': catalog:dev
    '@unocss/eslint-plugin': ^66.5.10
    '@vitest/ui': catalog:dev
    '@vue-macros/volar': ^3.1.1
    '@vue/test-utils': ^2.4.6
    dotenv: ^17.2.3
    eslint: ^9.39.2
    eslint-plugin-format: ^1.1.0
    lint-staged: ^16.2.7
    msw: ^2.12.4
    simple-git: ^3.30.0
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: catalog:dev
    vite-plugin-vue-devtools: ^8.0.5
    vitest: catalog:dev
    vue-tsc: ^3.1.8
  frontend:
    '@pinia/colada': ^0.18.1
    '@vee-validate/zod': ^4.15.1
    '@vueuse/core': ^14.1.0
    '@vueuse/integrations': ^14.1.0
    dayjs: ^1.11.19
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ky: ^1.14.1
    nanoid: ^5.1.6
    pinia: ^3.0.4
    pinia-plugin-persistedstate-2: ^2.0.32
    vee-validate: ^4.15.1
    vue: ^3.5.25
    vue-final-modal: ^4.5.5
    vue-router: ^4.6.4
    zod: ^4.2.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
