catalogMode: prefer

shellEmulator: true

trustPolicy: off

packages: []
catalogs:
  build:
    '@iconify-json/carbon': ^1.2.19
    '@iconify-json/tabler': ^1.2.31
    '@vitejs/plugin-vue': ^6.0.5
    jsdom: ^28.1.0
    unocss: ^66.6.6
    unplugin: ^3.0.0
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.19.1
    vite: ^8.0.0
  dev:
    '@antfu/eslint-config': ^7.7.2
    '@types/node': ^25.5.0
    '@unocss/eslint-plugin': ^66.6.6
    '@vitest/ui': ^4.1.0
    '@vue-macros/volar': ^3.1.2
    '@vue/test-utils': ^2.4.6
    dotenv: ^17.3.1
    eslint: ^10.0.3
    eslint-plugin-format: ^2.0.1
    lint-staged: ^16.3.3
    msw: ^2.12.10
    simple-git: ^3.33.0
    simple-git-hooks: ^2.13.1
    taze: ^19.10.0
    typescript: ^5.9.3
    vite-plugin-vue-devtools: ^8.0.7
    vitest: ^4.1.0
    vue-tsc: ^3.2.5
  frontend:
    '@pinia/colada': ^1.0.0
    '@vee-validate/zod': ^4.15.1
    '@vueuse/core': ^14.2.1
    '@vueuse/integrations': ^14.2.1
    dayjs: ^1.11.20
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ky: ^1.14.3
    nanoid: ^5.1.6
    pinia: ^3.0.4
    pinia-plugin-persistedstate-2: ^2.0.32
    vee-validate: ^4.15.1
    vue: ^3.5.30
    vue-final-modal: ^4.5.5
    vue-router: ^5.0.3
    zod: ^4.3.6
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
