packages: []

catalogs:

  build:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/tabler': ^1.2.17
    '@vitejs/plugin-vue': ^5.2.3
    jsdom: ^26.1.0
    unocss: 66.1.0-beta.7
    unplugin: ^2.3.2
    unplugin-auto-import: ^19.1.2
    unplugin-vue-components: ^28.5.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.12.0
    vite: ^6.2.6

  dev:
    '@antfu/eslint-config': ^4.12.0
    '@types/node': ^22.14.1
    '@unocss/eslint-plugin': 66.1.0-beta.7
    '@vitest/ui': ^3.1.1
    '@vue-macros/volar': ^3.0.0-beta.8
    '@vue/test-utils': ^2.4.6
    dotenv: ^16.5.0
    eslint: ^9.24.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.1
    msw: ^2.7.5
    simple-git: ^3.27.0
    simple-git-hooks: ^2.12.1
    taze: ^19.0.4
    typescript: ^5.8.3
    vite-plugin-vue-devtools: ^7.7.2
    vitest: ^3.1.1
    vue-tsc: ^2.2.8

  frontend:
    '@pinia/colada': ^0.14.2
    '@vee-validate/zod': ^4.15.0
    '@vueuse/core': ^13.1.0
    '@vueuse/integrations': ^13.1.0

    dayjs: ^1.11.13
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    ky: ^1.8.1
    nanoid: ^5.1.5
    pinia: ^3.0.2
    pinia-plugin-persistedstate-2: ^2.0.30
    vee-validate: ^4.15.0
    vue: ^3.5.13
    vue-final-modal: ^4.5.5
    vue-router: ^4.5.0
    zod: ^3.24.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
